export enum Tables {
    Table_Users = 'users',
    Table_Proposals = 'proposals',
    Table_Logs = 'logs',
    Table_Rewards = 'rewards',
    Table_Points = 'points',
    Table_CountryCodes = 'country_codes',
    Table_Sessions = 'sessions',
    Table_Connections = 'connections',
    Table_Referrals = 'referrals',
    Table_TimeTracking = 'time_tracking',
    Table_Otp = 'otp',
    Table_ProposalMapping = 'proposal_mapping',
    Table_NotificationType = 'notificationtype',
    Table_Notification = 'notification',
    Table_Languages = 'languages',
    Table_Devices = 'devices',
    Table_CustomRewards = 'custome_rewards',
    Table_UserDeviceInfo = "Table_UserDeviceInfo"
}
